### ISSUE TITLE
Translations functions are not used properly

### ISSUE THREAD

**Issue by bmihelac** [ezrajrice/django_advanced_password_validation#8]
Currently, because `ngettext` for plural mesages  is aliased as `_`  gettext catalogs would be wrong. 

This is doucmented in Django documentation:
https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#standard-translation

> What functions may be aliased as _?
> Because of how xgettext (used by [makemessages](https://docs.djangoproject.com/en/4.2/ref/django-admin/#django-admin-makemessages)) works, only functions that take a single string argument can be imported as _:
> [gettext()](https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.translation.gettext)
[gettext_lazy()](https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.translation.gettext_lazy)

Also, I propose to use lazy translations.

**Comment by bmihelac** [comment]
In other commits there are more gettext related fixes and I have added `special_characters` to help text and message, as user should know which special characters she can use and adding them in translation catalog is difficult to escape. I have updated tests for this.

@ezrajrice please let me know if anything else is needed regarding this

**Comment by bmihelac** [comment]
PR: https://github.com/ezrajrice/django_advanced_password_validation/pull/9

**Comment by ezrajrice** [comment]
@alex-a-pereira I apologize for the inconvenience. Life got in the way when I was setting up my automated deployment to PyPI and I forgot to make sure the fixes got there. There is a new version on PyPI and a new Release here on GitHub (see [v1.2.0](https://github.com/ezrajrice/django_advanced_password_validation/releases/tag/v1.2.0)). I specifically added testing for your version of Django and Python combination and the build is currently passing the tests.
